Repository Manohar-mj/Complete-Interview-Preparation---Self-Paced, pull requests merged in 2022-10, with the labels that each got.

#1 hactoberfest-2022
  soring/SelectionSort.java
Labels: hactoberfest

#2 hacktoberfest
  soring/selectionSort.cpp
Labels: hacktoberfest

#3 Update Print 1 To N Without Loop
  recursion/Print 1 To N Without Loop
Labels: hacktoberfest

#4 Create moveToFront.java
  moveToFront.java
Labels: hacktoberfest-accepted

#9 Update README.md
  README.md
Labels: hacktoberfest-accepted

#8 Create backtracking
  Backtracking/PhoneNumberLetterCombinations.cpp
  Backtracking/StringPermutations.cpp
Labels: hacktoberfest-accepted

#7 Create Remove Invalid Parentheses.java
  Backtracking Problems/Remove Invalid Parentheses.java
Labels: hacktoberfest-accepted

#10 Hacktoberfest Create NQueens.java
  Backtracking Problems/NQueens.java
Labels: hacktoberfest-accepted

#11 create quickSort.java
  soring/quickSort.java
Labels: hacktoberfest-accepted

#12 backtracking
  N queen problem .cpp
  print all palindrome of string.cpp
Labels: hacktoberfest-accepted

#13 Update README.md
  README.md
Labels: hacktoberfest-accepted

#14 Next Permutation.cpp
  Arrays & String/Next Permutation.cpp
Labels: hacktoberfest-accepted

#15 Binary Search.java
  Searching/Binary Search.java
Labels: hacktoberfest-accepted

#20 Search insert postition
  Searching/Find Smallest Letter Greater Than Target.java
  Searching/Search in Rotated Sorted Array.java
  Searching/search insert position.java
Labels: hacktoberfest-accepted

#21 CyclicSort.java
  CyclicSort.java
Labels: hacktoberfest-accepted

#22 Singlylinkedlist.java
  Singlylinkedlist.java
Labels: hacktoberfest-accepted
